### ISSUE TITLE
self.s.open() gives an error "ERROR: Port is already open."

### ISSUE THREAD

**Issue by zoobab** [devttys0/serio#1]
self.s.open() gives an error "ERROR: Port is already open.":

```
$ sudo ./serio.py -s /home/zoobab/memo -d /tmp/memo -p /dev/vmodem1 
ERROR: Port is already open.
```

If I comment the line 19 containing self.s.open(), it works fine.

See also this discussion:

https://github.com/turtlebot/turtlebot_create/issues/17

**Comment by devttys0** [comment]
Fixed, thanks!

**Comment by zoobab** [comment]
I am also linking it from this article:

http://www.zoobab.com/esp8266-serial2wifi-bridge#toc5
